### ISSUE TITLE
Some colors don't match image properly

### ISSUE THREAD

**Issue by BvngeeCord** [InioX/matugen#39] opened 2023-12-23 06:34 UTC
Thank you very much for this project! I should clarify, this very much could be a non-issue or a material-color-utilities-rs problem and not a Matugen one; please let me know if so. 

I was trying to use Matugen to create a GTK3/4 theme based on my wallpaper (the exact same thing that [Gradience](https://github.com/GradienceTeam/Gradience) can do but I wanted to use Matugen to be able to theme many different things). After setting the wallpaper and rebuilding, I noticed the colors didn't match up at all. My apps were a bright blue color, while the wallpaper contains only a small amount of very muted blue/teal:
![alena-aenami-budapest](https://github.com/InioX/matugen/assets/69218859/dcf28965-a9a6-4e41-814c-28f710e75805)

After a while of debugging, I believe I've narrowed the issue down to either Matugen or material-color-utilities-rs. Here is what the official Material Theme Builder produces (very understandably):
![20231222_22h01m22s_grim](https://github.com/InioX/matugen/assets/69218859/5372b73c-fd6d-40c8-ba07-f0d3c278c521)
Lastly, heres a comparison of the JSON output of Matugen (`matugen image Downloads/alena-aenami-budapest.jpg --json hex | jq`) vs material_color_utilities_python (using the exact same python script [that Gradience uses](https://github.com/GradienceTeam/Gradience/blob/c878099d15a5488c5d6b4bc6dbb1a283a3032da0/gradience/backend/theming/monet.py#L38)) vs the theme builder, all on dark mode:
![20231222_22h15m17s_grim](https://github.com/InioX/matugen/assets/69218859/fce83c0b-5457-414b-9438-c9e65e3a5a6f)
IMO, Matugen's output does not follow the image. However, it's interesting that *some* of the colors seem to match the other two outputs almost exactly (eg. "error"). 

I should also mention that I tried this with two other wallpapers as well; Matugen did better slightly better following the other two, but seemed to sway extra towards blue comparatively (this could probably use more testing).

Please let me know if you have any ideas what might be causing this, and if you think I should instead report it to material-color-utilities-rs!

**Comment by InioX** [comment] 2023-12-23 08:17
Hi, @BvngeeCord !

Thanks for the very detailed issue! I have also noticed this happening, but only when providing an image that is either black or white.

The issue should be with the `material_color_utilities_rs::score::score` function, especially these lines:
https://github.com/InioX/matugen/blob/fd262c1f8d328fab7db833040397b30c23a37100/material-color-utilities-rs/src/score.rs#L103-L109C6

I guess I'll try looking at the difference between the Rust, JavaScript, and Python implementations of this function. I wouldn't really rely on someone solving the issue in the original material-color-utilities-rs repo, as it has been inactive for a while.

**Comment by InioX** [comment] 2023-12-23 13:22
Could you try comparing the outputs again on the latest commit? I tried generating with the same image as you did and the source color changed to one that seems to match it.

### Before:
<img src="https://github.com/InioX/matugen/assets/81521595/be4d35f1-51f1-4791-b7d7-6588f67fd24d" width=50%>

### After:
<img src="https://github.com/InioX/matugen/assets/81521595/851432fc-62f1-4300-800c-660b53f40b79" width=50%>

**Comment by BvngeeCord** [comment] 2023-12-25 04:09
Can confirm, the output looks much better! I will try applying my GTK theme in a moment. Thanks for the quick response.

**Comment by linuxmobile** [comment] 2024-01-23 21:25
I am using version 1.2.2 but it seems to have the same problem as this issue!

![image](https://github.com/InioX/matugen/assets/10554636/c8d06277-f55e-4378-90d7-d6bf84df7082)

IMAGE: https://i.imgur.com/wgdLyPc.jpg

**Comment by InioX** [comment] 2024-01-29 17:43
Hi, after trying with the same image on the `dev` branch i managed to get a more accurate result.

Image used: https://imgur.com/wgdLyPc

### Before:

![image](https://github.com/InioX/matugen/assets/81521595/6a70799d-2303-4d92-a8e7-daad24139bba)

```json
{
   "colors":{
      "amoled":{
         "error":"#ffb4ab",
         "error_container":"#93000a",
         "inverse_on_surface":"#2f3035",
         "inverse_primary":"#005ac1",
         "inverse_surface":"#e3e2e8",
         "on_error":"#690005",
         "on_error_container":"#ffb4ab",
         "on_primary":"#002e69",
         "on_primary_container":"#d8e2ff",
         "on_primary_fixed":"#001a41",
         "on_primary_fixed_variant":"#004494",
         "on_secondary":"#253048",
         "on_secondary_container":"#d8e2ff",
         "on_secondary_fixed":"#0f1b32",
         "on_secondary_fixed_variant":"#3b475f",
         "on_surface":"#e3e2e8",
         "on_surface_variant":"#c4c6d0",
         "on_tertiary":"#44244a",
         "on_tertiary_container":"#fed6ff",
         "on_tertiary_fixed":"#2d0e34",
         "on_tertiary_fixed_variant":"#5d3a62",
         "outline":"#8e9099",
         "outline_variant":"#44474f",
         "primary":"#adc6ff",
         "primary_container":"#004494",
         "primary_fixed":"#d8e2ff",
         "primary_fixed_dim":"#adc6ff",
         "scrim":"#000000",
         "secondary":"#bbc6e4",
         "secondary_container":"#3b475f",
         "secondary_fixed":"#d8e2ff",
         "secondary_fixed_dim":"#bbc6e4",
         "shadow":"#000000",
         "source_color":"#4285f4",
         "surface":"#000000",
         "surface_bright":"#faf9ff",
         "surface_container":"#eeedf3",
         "surface_container_high":"#e8e7ed",
         "surface_container_highest":"#e3e2e8",
         "surface_container_low":"#f4f3f9",
         "surface_container_lowest":"#ffffff",
         "surface_dim":"#dad9df",
         "tertiary":"#e5b8e8",
         "tertiary_container":"#5d3a62",
         "tertiary_fixed":"#fed6ff",
         "tertiary_fixed_dim":"#e5b8e8"
      },
      "dark":{
         "error":"#ffb4ab",
         "error_container":"#93000a",
         "inverse_on_surface":"#2f3035",
         "inverse_primary":"#005ac1",
         "inverse_surface":"#e3e2e8",
         "on_error":"#690005",
         "on_error_container":"#ffb4ab",
         "on_primary":"#002e69",
         "on_primary_container":"#d8e2ff",
         "on_primary_fixed":"#001a41",
         "on_primary_fixed_variant":"#004494",
         "on_secondary":"#253048",
         "on_secondary_container":"#d8e2ff",
         "on_secondary_fixed":"#0f1b32",
         "on_secondary_fixed_variant":"#3b475f",
         "on_surface":"#e3e2e8",
         "on_surface_variant":"#c4c6d0",
         "on_tertiary":"#44244a",
         "on_tertiary_container":"#fed6ff",
         "on_tertiary_fixed":"#2d0e34",
         "on_tertiary_fixed_variant":"#5d3a62",
         "outline":"#8e9099",
         "outline_variant":"#44474f",
         "primary":"#adc6ff",
         "primary_container":"#004494",
         "primary_fixed":"#d8e2ff",
         "primary_fixed_dim":"#adc6ff",
         "scrim":"#000000",
         "secondary":"#bbc6e4",
         "secondary_container":"#3b475f",
         "secondary_fixed":"#d8e2ff",
         "secondary_fixed_dim":"#bbc6e4",
         "shadow":"#000000",
         "source_color":"#4285f4",
         "surface":"#121317",
         "surface_bright":"#38393e",
         "surface_container":"#1e1f24",
         "surface_container_high":"#292a2e",
         "surface_container_highest":"#333539",
         "surface_container_low":"#1a1b20",
         "surface_container_lowest":"#0d0e12",
         "surface_dim":"#121317",
         "tertiary":"#e5b8e8",
         "tertiary_container":"#5d3a62",
         "tertiary_fixed":"#fed6ff",
         "tertiary_fixed_dim":"#e5b8e8"
      },
      "light":{
         "error":"#ba1a1a",
         "error_container":"#ffdad6",
         "inverse_on_surface":"#f1f0f6",
         "inverse_primary":"#adc6ff",
         "inverse_surface":"#2f3035",
         "on_error":"#ffffff",
         "on_error_container":"#410002",
         "on_primary":"#ffffff",
         "on_primary_container":"#001a41",
         "on_primary_fixed":"#001a41",
         "on_primary_fixed_variant":"#004494",
         "on_secondary":"#ffffff",
         "on_secondary_container":"#0f1b32",
         "on_secondary_fixed":"#0f1b32",
         "on_secondary_fixed_variant":"#3b475f",
         "on_surface":"#1a1b20",
         "on_surface_variant":"#44474f",
         "on_tertiary":"#ffffff",
         "on_tertiary_container":"#2d0e34",
         "on_tertiary_fixed":"#2d0e34",
         "on_tertiary_fixed_variant":"#5d3a62",
         "outline":"#74777f",
         "outline_variant":"#c4c6d0",
         "primary":"#005ac1",
         "primary_container":"#d8e2ff",
         "primary_fixed":"#d8e2ff",
         "primary_fixed_dim":"#adc6ff",
         "scrim":"#000000",
         "secondary":"#535e78",
         "secondary_container":"#d8e2ff",
         "secondary_fixed":"#d8e2ff",
         "secondary_fixed_dim":"#bbc6e4",
         "shadow":"#000000",
         "source_color":"#4285f4",
         "surface":"#faf9ff",
         "surface_bright":"#faf9ff",
         "surface_container":"#eeedf3",
         "surface_container_high":"#e8e7ed",
         "surface_container_highest":"#e3e2e8",
         "surface_container_low":"#f4f3f9",
         "surface_container_lowest":"#ffffff",
         "surface_dim":"#dad9df",
         "tertiary":"#76517b",
         "tertiary_container":"#fed6ff",
         "tertiary_fixed":"#fed6ff",
         "tertiary_fixed_dim":"#e5b8e8"
      }
   },
   "colors_android":{
      "amoled":{
         "accent_surface":"#edf0ff",
         "color_accent_primary":"#d8e2ff",
         "color_accent_primary_variant":"#80aaff",
         "color_accent_secondary":"#d8e2ff",
         "color_accent_secondary_variant":"#a0abc8",
         "color_accent_tertiary":"#fed6ff",
         "color_accent_tertiary_variant":"#c89dcb",
         "color_background":"#000000",
         "color_background_floating":"#000000",
         "color_surface":"#0f1115",
         "color_surface_highlight":"#1a1b20",
         "color_surface_variant":"#24262a",
         "off_state":"#2f3035",
         "scrim_android":"#c6c6cc",
         "source_color":"#4285f4",
         "surface_header":"#1a1b20",
         "text_color_primary":"#f1f0f6",
         "text_color_primary_inverse":"#1a1b20",
         "text_color_secondary":"#c4c6d0",
         "text_color_secondary_inverse":"#45464b",
         "text_color_tertiary":"#8e9099",
         "text_color_tertiary_inverse":"#76777c",
         "text_primary_on_accent":"#1a1b20",
         "text_secondary_on_accent":"#44474f",
         "under_surface":"#000000",
         "volume_background":"#000000"
      },
      "dark":{
         "accent_surface":"#edf0ff",
         "color_accent_primary":"#d8e2ff",
         "color_accent_primary_variant":"#80aaff",
         "color_accent_secondary":"#d8e2ff",
         "color_accent_secondary_variant":"#a0abc8",
         "color_accent_tertiary":"#fed6ff",
         "color_accent_tertiary_variant":"#c89dcb",
         "color_background":"#1a1b20",
         "color_background_floating":"#1a1b20",
         "color_surface":"#2f3035",
         "color_surface_highlight":"#515257",
         "color_surface_variant":"#45464b",
         "off_state":"#2f3035",
         "scrim_android":"#c6c6cc",
         "source_color":"#4285f4",
         "surface_header":"#45464b",
         "text_color_primary":"#f1f0f6",
         "text_color_primary_inverse":"#1a1b20",
         "text_color_secondary":"#c4c6d0",
         "text_color_secondary_inverse":"#45464b",
         "text_color_tertiary":"#8e9099",
         "text_color_tertiary_inverse":"#76777c",
         "text_primary_on_accent":"#1a1b20",
         "text_secondary_on_accent":"#44474f",
         "under_surface":"#000000",
         "volume_background":"#3a3b40"
      },
      "light":{
         "accent_surface":"#edf0ff",
         "color_accent_primary":"#d8e2ff",
         "color_accent_primary_variant":"#005ac1",
         "color_accent_secondary":"#d8e2ff",
         "color_accent_secondary_variant":"#535e78",
         "color_accent_tertiary":"#fed6ff",
         "color_accent_tertiary_variant":"#76517b",
         "color_background":"#f1f0f6",
         "color_background_floating":"#faf9ff",
         "color_surface":"#faf9ff",
         "color_surface_highlight":"#ffffff",
         "color_surface_variant":"#e3e2e8",
         "off_state":"#2f3035",
         "scrim_android":"#c6c6cc",
         "source_color":"#4285f4",
         "surface_header":"#e3e2e8",
         "text_color_primary":"#1a1b20",
         "text_color_primary_inverse":"#f1f0f6",
         "text_color_secondary":"#44474f",
         "text_color_secondary_inverse":"#c6c6cc",
         "text_color_tertiary":"#74777f",
         "text_color_tertiary_inverse":"#909096",
         "text_primary_on_accent":"#1a1b20",
         "text_secondary_on_accent":"#44474f",
         "under_surface":"#000000",
         "volume_background":"#3a3b40"
      }
   }
}
```

### After:

![image](https://github.com/InioX/matugen/assets/81521595/e7449c78-1658-4149-bb99-665b0bff95af)

```json
{
   "colors":{
      "dark":{
         "background":"#111318",
         "error":"#ffb4ab",
         "error_container":"#93000a",
         "inverse_on_surface":"#2f3036",
         "inverse_primary":"#445e91",
         "inverse_surface":"#e2e2e9",
         "on_background":"#e2e2e9",
         "on_error":"#690005",
         "on_error_container":"#ffdad6",
         "on_primary":"#102f60",
         "on_primary_container":"#d8e2ff",
         "on_primary_fixed":"#001a41",
         "on_primary_fixed_variant":"#2b4678",
         "on_secondary":"#293041",
         "on_secondary_container":"#dbe2f9",
         "on_secondary_fixed":"#141b2c",
         "on_secondary_fixed_variant":"#3f4759",
         "on_surface":"#e2e2e9",
         "on_surface_variant":"#c4c6d0",
         "on_tertiary":"#402843",
         "on_tertiary_container":"#fbd7fc",
         "on_tertiary_fixed":"#29132d",
         "on_tertiary_fixed_variant":"#583e5b",
         "outline":"#8e9099",
         "outline_variant":"#44474f",
         "primary":"#adc6ff",
         "primary_container":"#2b4678",
         "primary_fixed":"#d8e2ff",
         "primary_fixed_dim":"#adc6ff",
         "scrim":"#000000",
         "secondary":"#bfc6dc",
         "secondary_container":"#bfc6dc",
         "secondary_fixed":"#dbe2f9",
         "secondary_fixed_dim":"#bfc6dc",
         "shadow":"#000000",
         "surface":"#111318",
         "surface_bright":"#37393e",
         "surface_container":"#1e1f25",
         "surface_container_high":"#282a2f",
         "surface_container_highest":"#33353a",
         "surface_container_low":"#1a1b20",
         "surface_container_lowest":"#0c0e13",
         "surface_dim":"#111318",
         "surface_variant":"#44474f",
         "tertiary":"#debcdf",
         "tertiary_container":"#583e5b",
         "tertiary_fixed":"#fbd7fc",
         "tertiary_fixed_dim":"#debcdf"
      },
      "light":{
         "background":"#f9f9ff",
         "error":"#ba1a1a",
         "error_container":"#ffdad6",
         "inverse_on_surface":"#f0f0f7",
         "inverse_primary":"#adc6ff",
         "inverse_surface":"#2f3036",
         "on_background":"#1a1b20",
         "on_error":"#ffffff",
         "on_error_container":"#410002",
         "on_primary":"#ffffff",
         "on_primary_container":"#001a41",
         "on_primary_fixed":"#001a41",
         "on_primary_fixed_variant":"#2b4678",
         "on_secondary":"#ffffff",
         "on_secondary_container":"#141b2c",
         "on_secondary_fixed":"#141b2c",
         "on_secondary_fixed_variant":"#3f4759",
         "on_surface":"#1a1b20",
         "on_surface_variant":"#44474f",
         "on_tertiary":"#ffffff",
         "on_tertiary_container":"#29132d",
         "on_tertiary_fixed":"#29132d",
         "on_tertiary_fixed_variant":"#583e5b",
         "outline":"#74777f",
         "outline_variant":"#c4c6d0",
         "primary":"#445e91",
         "primary_container":"#d8e2ff",
         "primary_fixed":"#d8e2ff",
         "primary_fixed_dim":"#adc6ff",
         "scrim":"#000000",
         "secondary":"#575e71",
         "secondary_container":"#575e71",
         "secondary_fixed":"#dbe2f9",
         "secondary_fixed_dim":"#bfc6dc",
         "shadow":"#000000",
         "source_color":"#4285f4",
         "surface":"#f9f9ff",
         "surface_bright":"#f9f9ff",
         "surface_container":"#ededf4",
         "surface_container_high":"#e8e7ee",
         "surface_container_highest":"#e2e2e9",
         "surface_container_low":"#f3f3fa",
         "surface_container_lowest":"#ffffff",
         "surface_dim":"#d9d9e0",
         "surface_variant":"#e1e2ec",
         "tertiary":"#715573",
         "tertiary_container":"#fbd7fc",
         "tertiary_fixed":"#fbd7fc",
         "tertiary_fixed_dim":"#debcdf"
      }
   }
}
```

**Comment by linuxmobile** [comment] 2024-01-29 20:02
> Hi, after trying with the same image on the `dev` branch i managed to get a more accurate result.

I already check the `dev` branch and color matching is better. But I don't want to jump from branch to branch to get the color right! Which version or branch should I really use? Sorry if my language seems a bit demanding, it really isn't!


```
{
   "colors":{
      "dark":{
         "background":"#191114",
         "error":"#ffb4ab",
         "error_container":"#93000a",
         "inverse_on_surface":"#372e31",
         "inverse_primary":"#894a68",
         "inverse_surface":"#eedfe3",
         "on_background":"#eedfe3",
         "on_error":"#690005",
         "on_error_container":"#ffdad6",
         "on_primary":"#531d38",
         "on_primary_container":"#ffd8e6",
         "on_primary_fixed":"#390723",
         "on_primary_fixed_variant":"#6e334f",
         "on_secondary":"#412a33",
         "on_secondary_container":"#fed9e6",
         "on_secondary_fixed":"#2a151e",
         "on_secondary_fixed_variant":"#593f4a",
         "on_surface":"#eedfe3",
         "on_surface_variant":"#d4c2c7",
         "on_tertiary":"#49280f",
         "on_tertiary_container":"#ffdcc6",
         "on_tertiary_fixed":"#301401",
         "on_tertiary_fixed_variant":"#633e23",
         "outline":"#9d8c92",
         "outline_variant":"#504348",
         "primary":"#feb0d1",
         "primary_container":"#6e334f",
         "primary_fixed":"#ffd8e6",
         "primary_fixed_dim":"#feb0d1",
         "scrim":"#000000",
         "secondary":"#e1bdca",
         "secondary_container":"#e1bdca",
         "secondary_fixed":"#fed9e6",
         "secondary_fixed_dim":"#e1bdca",
         "shadow":"#000000",
         "surface":"#191114",
         "surface_bright":"#40373a",
         "surface_container":"#251d20",
         "surface_container_high":"#30282b",
         "surface_container_highest":"#3b3235",
         "surface_container_low":"#21191c",
         "surface_container_lowest":"#130c0f",
         "surface_dim":"#191114",
         "surface_variant":"#504348",
         "tertiary":"#f2bb98",
         "tertiary_container":"#633e23",
         "tertiary_fixed":"#ffdcc6",
         "tertiary_fixed_dim":"#f2bb98"
      },
      "light":{
         "background":"#fff8f8",
         "error":"#ba1a1a",
         "error_container":"#ffdad6",
         "inverse_on_surface":"#fdedf1",
         "inverse_primary":"#feb0d1",
         "inverse_surface":"#372e31",
         "on_background":"#21191c",
         "on_error":"#ffffff",
         "on_error_container":"#410002",
         "on_primary":"#ffffff",
         "on_primary_container":"#390723",
         "on_primary_fixed":"#390723",
         "on_primary_fixed_variant":"#6e334f",
         "on_secondary":"#ffffff",
         "on_secondary_container":"#2a151e",
         "on_secondary_fixed":"#2a151e",
         "on_secondary_fixed_variant":"#593f4a",
         "on_surface":"#21191c",
         "on_surface_variant":"#504348",
         "on_tertiary":"#ffffff",
         "on_tertiary_container":"#301401",
         "on_tertiary_fixed":"#301401",
         "on_tertiary_fixed_variant":"#633e23",
         "outline":"#827378",
         "outline_variant":"#d4c2c7",
         "primary":"#894a68",
         "primary_container":"#ffd8e6",
         "primary_fixed":"#ffd8e6",
         "primary_fixed_dim":"#feb0d1",
         "scrim":"#000000",
         "secondary":"#735762",
         "secondary_container":"#735762",
         "secondary_fixed":"#fed9e6",
         "secondary_fixed_dim":"#e1bdca",
         "shadow":"#000000",
         "source_color":"#1e1217",
         "surface":"#fff8f8",
         "surface_bright":"#fff8f8",
         "surface_container":"#faeaee",
         "surface_container_high":"#f4e4e8",
         "surface_container_highest":"#eedfe3",
         "surface_container_low":"#fff0f3",
         "surface_container_lowest":"#ffffff",
         "surface_dim":"#e5d6da",
         "surface_variant":"#f1dee3",
         "tertiary":"#7e5538",
         "tertiary_container":"#ffdcc6",
         "tertiary_fixed":"#ffdcc6",
         "tertiary_fixed_dim":"#f2bb98"
      }
   }
}
```

**Comment by InioX** [comment] 2024-01-30 04:26
Hi, @linuxmobile !

I haven't pushed to main branch yet because of https://github.com/Aiving/material-colors/issues/4

**Comment by InioX** [comment] 2024-02-01 10:06
The issue is resolved now so I will make a new release.

**Comment by linuxmobile** [comment] 2024-02-01 13:50
> The issue is resolved now so I will make a new release.

Ulala! I will try right now!

**Comment by PoSayDone** [comment] 2024-02-01 19:30
for me, the colors don't match in many pictures after the update(
(Also --show-colors order is random for some reason)

<details>
<summary>Example one</summary>
material theme builder:

![image](https://github.com/InioX/matugen/assets/29358657/5c6f95b5-bd9b-4181-9592-2290854113f8)

matugen:

![image](https://github.com/InioX/matugen/assets/29358657/999a638e-f475-4c02-857e-27abb2631aaa)

source:
https://i.imgur.com/AoaBp86.jpeg
</details>

<details>
<summary>Example two</summary>
material theme builder:

![image](https://github.com/InioX/matugen/assets/29358657/45b5adae-a964-41b2-9109-4d226316d48a)

matugen:

![image](https://github.com/InioX/matugen/assets/29358657/fa7dc04a-26c0-40ac-b3c9-94b65e6eae82)

soruce:
https://i.imgur.com/u7OjTQz.jpeg
</details>

**Comment by PoSayDone** [comment] 2024-02-01 19:46
Opened an issue:
Aiving/material-colors#5

**Comment by InioX** [comment] 2024-02-02 05:11
> for me, the colors don't match in many pictures after the update( (Also --show-colors order is random for some reason)
> Example one
> material theme builder:
> Example two
> material theme builder:
> 
> UPD: I've checked colors using simple example, and that is the new library issue:
> Code
> 
> result for example two using this code: ![image](https://private-user-images.githubusercontent.com/29358657/301625271-4302f87d-e5c1-45db-bb2f-081fde8e5388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTA3NzIsIm5iZiI6MTcwNjg1MDQ3MiwicGF0aCI6Ii8yOTM1ODY1Ny8zMDE2MjUyNzEtNDMwMmY4N2QtZTVjMS00NWRiLWJiMmYtMDgxZmRlOGU1Mzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA1MDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyN2Y3NDA2NjJhNjM5OGY1ZmM3ODY3ZjdkNDcxZmI5MmZmYWY1Y2ZhYTNhMGViZWQwOTQ1YjIzNWY3ODQ3NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J0vpMrg9OPL43RZpAHsDFklEflN_a5rO8loC6HtnDZU)

The `--show-color` order is random because it is using a HashMap now. I can try to fix it somehow.

**Comment by PoSayDone** [comment] 2024-02-02 05:47
There's also another issue with mismatched colors on Aiving/material-colors#5, but it's fixed in git so waiting for changes show up in cargo.

**Comment by InioX** [comment] 2024-02-02 17:08
Now that the issue in `material-colors` has been resolved and a new release has been made, I will bump the version and try.

**Comment by InioX** [comment] 2024-02-02 18:42
Also `--show-colors` color order is fixed now.

**Closed** 2024-02-05 14:04 UTC
